version: "3.3"
services:
  fastify:
    image: landscapedatacommons/fast_api:1.0.0
    build:
      context: ./src
      dockerfile: node.Dockerfile
    ports:
      - "5017:3000"
    env_file:
      - ./src/.env

    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy: 
        condition: on-failure