const geoIndicatorsSchema = {
  $id: 'geoIndicators',
  type: 'object',
    properties: {
      rid: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      PrimaryKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      DBKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      ProjectKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      DateVisited: { anyOf: [{ type: 'string', format: 'date' }, { type: 'array', items: { type: 'string', format: 'date' } }] },
      EcologicalSiteId: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      PercentCoveredByEcoSite: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Latitude_NAD83: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Longitude_NAD83: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      LocationStatus: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      LocationType: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      Latitude_NAD83_Actual: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Longitude_NAD83_Actual: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      BareSoilCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      TotalFoliarCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      AH_AnnGrassCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      AH_ForbCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      AH_GrassCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      AH_PerenForbCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      AH_PerenForbGrassCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      AH_PerenGrassCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      AH_ShrubCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_CyanobacteriaCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_DepSoilCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_DuffCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_EmbLitterCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_HerbLitterCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_LichenCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_MossCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_RockCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_TotalLitterCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_VagrLichenCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_WaterCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      FH_WoodyLitterCover: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      GapCover_101_200: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      GapCover_200_plus: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      GapCover_25_50: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      GapCover_25_plus: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      GapCover_51_100: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Hgt_Forb_Avg: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Hgt_Grass_Avg: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Hgt_Herbaceous_Avg: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Hgt_PerenForb_Avg: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Hgt_PerenForbGrass_Avg: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Hgt_PerenGrass_Avg: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Hgt_Woody_Avg: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      RH_AnnualProd: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_BareGround: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_BioticIntegrity: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_CommentsBI: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_CommentsHF: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_CommentsSS: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_Compaction: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_DeadDyingPlantParts: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_FuncSructGroup: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_Gullies: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_HydrologicFunction: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_InvasivePlants: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_LitterAmount: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_LitterMovement: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_PedestalsTerracettes: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_PlantCommunityComp: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_ReprodCapabilityPeren: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_Rills: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_SoilSiteStability: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_SoilSurfLossDeg: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_SoilSurfResisErosion: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_WaterFlowPatterns: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      RH_WindScouredAreas: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      SoilStability_All: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      SoilStability_Protected: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      SoilStability_Unprotected: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      DateLoadedInDb: { anyOf: [{ type: 'string', format: 'date' }, { type: 'array', items: { type: 'string', format: 'date' } }] },
      mlra_name: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      mlrarsym: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      na_l1name: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      na_l2name: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      us_l3name: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      us_l4name: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      State: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] }, 
      modis_landcover:{ anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] }, 
      wkb_geometry: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] }
    }
  } 

  module.exports = geoIndicatorsSchema