const tblRHEMSchema = {
  $id:'tblRHEM',
  type: 'object',
  properties: {
    ProjectKey: { oneOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
    PrimaryKey: { oneOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
    Precipitation_Long_Term_MEAN: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Long_Term_MEAN: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Long_Term_MEAN: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Long_Term_MEAN: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Maximum_Daily_2_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Maximum_Daily_5_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Maximum_Daily_10_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Maximum_Daily_25_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Maximum_Daily_50_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Maximum_Daily_100_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Totals_2_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Totals_5_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Totals_10_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Totals_25_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Totals_50_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Precipitation_Yearly_Totals_100_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Maximum_Daily_2_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Maximum_Daily_5_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Maximum_Daily_10_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Maximum_Daily_25_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Maximum_Daily_50_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Maximum_Daily_100_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Totals_2_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Totals_5_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Totals_10_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Totals_25_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Totals_50_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Runoff_Annual_Totals_100_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Maximum_Daily_2_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Maximum_Daily_5_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Maximum_Daily_10_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Maximum_Daily_25_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Maximum_Daily_50_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Maximum_Daily_100_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Totals_2_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Totals_5_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Totals_10_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Totals_25_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Totals_50_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Soil_Loss_Yearly_Totals_100_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Maximum_Daily_2_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Maximum_Daily_5_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Maximum_Daily_10_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Maximum_Daily_25_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Maximum_Daily_50_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Maximum_Daily_100_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Totals_2_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Totals_5_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Totals_10_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Totals_25_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Totals_50_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    Sediment_Yield_Yearly_Totals_100_YR: { oneOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
    DBKey: { oneOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
    DateLoadedInDB: { oneOf: [{ type: "string", format: "date" }, { type: "array", items: { type: "string", format: "date" } }]},
  }
}
module.exports = tblRHEMSchema