const dataHeightSchema = {
  $id: 'dataHeight',
  type: 'object',
    properties: {
      rid: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      PrimaryKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      DBKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      ProjectKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      PointLoc: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      PointNbr: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      RecKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      Height: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Species: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      Chkbox: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      type: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      GrowthHabit_measured: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      LineKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      DateModified: { anyOf: [{ type: 'string', format: 'date' }, { type: 'array', items: { type: 'string', format: 'date' } }] },
      FormType: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      FormDate: { anyOf: [{ type: 'string', format: 'date' }, { type: 'array', items: { type: 'string', format: 'date' } }] },
      source: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      Direction: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      Measure: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      LineLengthAmount: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      SpacingIntervalAmount: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      SpacingType: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      HeightOption: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      HeightUOM: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      ShowCheckbox: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      CheckboxLabel: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      DateLoadedInDb: { anyOf: [{ type: 'string', format: 'date' }, { type: 'array', items: { type: 'string', format:'date' } }] },
      DateVisited: { anyOf: [{ type: 'string', format: 'date' }, { type: 'array', items: { type: 'string', format:'date' } }] },
    },
  }
module.exports = dataHeightSchema
