const dataGapSchema = {
  type: 'object',
  properties: {
    rid: { type: 'integer', nullable: true },
    PrimaryKey: { type: 'string', nullable: true },
    DBKey: { type: 'string', nullable: true },
    ProjectKey: { type: 'string', nullable: true },
    RecType: { type: 'string', nullable: true },
    SeqNo: { type: 'integer', nullable: true },
    GapStart: { type: 'number', nullable: true },
    GapEnd: { type: 'number', nullable: true },
    Gap: { type: 'number', nullable: true },
    LineKey: { type: 'string', nullable: true },
    RecKey: { type: 'string', nullable: true },
    FormDate: { type: 'string', format: 'date', nullable: true },
    DateModified: { type: 'string', format: 'date', nullable: true },
    FormType: { type: 'string', nullable: true },
    Direction: { type: 'string', nullable: true },
    Measure: { type: 'integer', nullable: true },
    LineLengthAmount: { type: 'number', nullable: true },
    GapMin: { type: 'number', nullable: true },
    GapData: { type: 'integer', nullable: true },
    PerennialsCanopy: { type: 'boolean', nullable: true },
    AnnualGrassesCanopy: { type: 'boolean', nullable: true },
    AnnualForbsCanopy: { type: 'boolean', nullable: true },
    OtherCanopy: { type: 'boolean', nullable: true },
    Notes: { type: 'string', nullable: true },
    NoCanopyGaps: { type: 'integer', nullable: true },
    NoBasalGaps: { type: 'integer', nullable: true },
    DateLoadedInDb: { type: 'string', format: 'date', nullable: true },
    PerennialsBasal: { type: 'boolean', nullable: true },
    AnnualGrassesBasal: { type: 'boolean', nullable: true },
    AnnualForbsBasal: { type: 'boolean', nullable: true },
    OtherBasal: { type: 'boolean', nullable: true },
    source: { type: 'string', nullable: true },
    DateVisited: { type: 'string', format: 'date', nullable: true },
  },
  // required: [
  //   'rid',
  //   'PrimaryKey',
  //   'DBKey',
  //   'ProjectKey',
  //   'RecType',
  //   'SeqNo',
  //   'GapStart',
  //   'GapEnd',
  //   'Gap',
  //   'LineKey',
  //   'RecKey',
  //   'FormDate',
  //   'DateModified',
  //   'FormType',
  //   'Direction',
  //   'Measure',
  //   'LineLengthAmount',
  //   'GapMin',
  //   'GapData',
  //   'PerennialsCanopy',
  //   'AnnualGrassesCanopy',
  //   'AnnualForbsCanopy',
  //   'OtherCanopy',
  //   'Notes',
  //   'NoCanopyGaps',
  //   'NoBasalGaps',
  //   'DateLoadedInDb',
  //   'PerennialsBasal',
  //   'AnnualGrassesBasal',
  //   'AnnualForbsBasal',
  //   'OtherBasal',
  //   'source',
  //   'DateVisited',
  // ],
};

module.exports = dataGapSchema
// Register the JSON schema with Fastify
// fastify.addSchema(schema);