const dataHorizontalFlux = {
    $id: 'dataHorizontalFlux',
    type: 'object',
    properties: {
      rid: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      ProjectKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      PrimaryKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      BoxID: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      StackID: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      Height: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      DateEstablished: { anyOf: [{ type: 'string', format: 'date' }, { type: 'array', items: { type: 'string', format: 'date' } }] },
      Description: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      openingSize: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      processMethod: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      ovenTemp: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      BoxType: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      azimuth: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      SamplerType: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      InletArea: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Location: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      ItemType: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      trapOpeningArea: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      GPSCoordSys: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      Datum: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      Zone: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      Easting: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Northing: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Longitude: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      Latitude: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      RecKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      collectDate: { anyOf: [{ type: 'string', format: 'date' }, { type: 'array', items: { type: 'string', format: 'date' } }] },
      beakerNbr: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      emptyWeight: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      recordedWeight: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      sedimentWeight: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      daysExposed: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      sedimentGperDay: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      sedimentArchived: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      Notes: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      sedimentGperDayByInlet: { anyOf: [{ type: 'number' }, { type: 'array', items: { type: 'number' } }] },
      SeqNo: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      SampleCompromised: { anyOf: [{ type: 'integer' }, { type: 'array', items: { type: 'integer' } }] },
      DBKey: { anyOf: [{ type: 'string' }, { type: 'array', items: { type: 'string' } }] },
      DateLoadedInDb: { anyOf: [{ type: 'string', format: 'date' }, { type: 'array', items: { type: 'string', format: 'date' } }] },
      DateVisited: { anyOf: [{ type: 'string', format: 'date' }, { type: 'array', items: { type: 'string', format: 'date' } }] },
    }
  }

module.exports = dataHorizontalFlux